apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: flask.example.com
      http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-web-app
            port:
              number: 80