apiVersion: v1
kind: Service
metadata:
  name: flask-web-app
  labels:
    app: flask-web-app
spec:
  selector:
    app: flask-web-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
