# CICD using GitHub actions

name: CI/CD

# Exclude the workflows to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-web-app:${{github.run_id}}

#  update-newtag-in-helm-chart:
#    runs-on: ubuntu-latest
#
#    needs: push
#
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v4
#      with:
#        token: ${{ secrets.TOKEN }}
#
#    - name: Update tag in Helm chart
#      run: |
#        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
#
#    - name: Commit and push changes
#      run: |
#        git add helm/go-web-app-chart/values.yaml
#        git commit -m "Update tag in Helm chart"
#        git push

